import {
  Atom,
  BookOpen,
  Brain,
  Briefcase,
  Calculator,
  Camera,
  ChartLine,
  ChefHat,
  Code,
  Coffee,
  Compass,
  Dna,
  Dumbbell,
  FlaskConical,
  Gavel,
  Globe,
  GraduationCap,
  Guitar,
  Heart,
  Landmark,
  Languages,
  Leaf,
  Lightbulb,
  Map,
  Microscope,
  Mountain,
  Music,
  Palette,
  PawPrint,
  Pill,
  Plane,
  Rocket,
  Scale,
  Sigma,
  Sparkles,
  Stethoscope,
  Sun,
  Target,
  Trophy,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

/** Curated project icons; the key (lucide name) is stored in Project.icon. */
export const PROJECT_ICONS = {
  languages: Languages,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  brain: Brain,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  target: Target,
  trophy: Trophy,
  globe: Globe,
  map: Map,
  compass: Compass,
  plane: Plane,
  landmark: Landmark,
  briefcase: Briefcase,
  'chart-line': ChartLine,
  wallet: Wallet,
  scale: Scale,
  gavel: Gavel,
  calculator: Calculator,
  sigma: Sigma,
  atom: Atom,
  'flask-conical': FlaskConical,
  microscope: Microscope,
  dna: Dna,
  stethoscope: Stethoscope,
  pill: Pill,
  heart: Heart,
  leaf: Leaf,
  'paw-print': PawPrint,
  mountain: Mountain,
  sun: Sun,
  code: Code,
  rocket: Rocket,
  music: Music,
  guitar: Guitar,
  palette: Palette,
  camera: Camera,
  'chef-hat': ChefHat,
  coffee: Coffee,
  dumbbell: Dumbbell,
} as const satisfies Record<string, LucideIcon>;

export type ProjectIconName = keyof typeof PROJECT_ICONS;

export function projectIcon(name: string | undefined): LucideIcon | undefined {
  return name && name in PROJECT_ICONS ? PROJECT_ICONS[name as ProjectIconName] : undefined;
}

/** CSS color of a project palette token, e.g. var(--project-indigo). */
export function projectColor(color: string, soft = false): string {
  return `var(--project-${color}${soft ? '-soft' : ''})`;
}
